# Generated by Django 2.1.2 on 2018-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bigfit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
