# Generated by Django 2.1.3 on 2018-12-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bigfit', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
